version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: "harbor.linkorb.com/linkorb/http-spool-server"
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Connect to Harbor
          command: |
            echo "$DOCKER_PASSWORD" | docker login harbor.linkorb.com -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Harbor
          command: docker push $IMAGE_NAME:latest
      - run:
          name: Update service on Swarm cluster
          command: curl -X POST $UPDATE_HOOK
workflows:
  version: 2
  build-master:
    jobs:
      - build
